meta_product_name: "Scrabble Helper"
meta_title: "Scrabble Helper - Cheat or Train your way to winning!"
meta_description: "The first bilingual (French and English) Scrabble helper, ask us to find the longest words with your letters, or increase your skill by playing our fun game!"
meta_image: "thumbnail.jpg" # should exist in `app/assets/images/`